# Generated by Django 4.1.2 on 2022-11-02 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo_doctor',
            field=models.ImageField(default='null', null=True, upload_to='imgs/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='schedule_details',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
