# Generated by Django 4.1.3 on 2022-11-26 13:31

import django.core.validators
from django.db import migrations, models
import sys_base.models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0003_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='iin',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12), sys_base.models.charfield_is_number_validator]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middlename',
            field=models.CharField(default='', max_length=30),
        ),
    ]
