# Generated by Django 4.1.3 on 2022-11-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0004_remove_patient_id_alter_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminStaff',
        ),
    ]
