# Generated by Django 4.1.3 on 2022-12-06 15:26

import django.core.validators
from django.db import migrations, models
import sys_base.models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0004_alter_patient_address_alter_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='iin',
            field=models.CharField(blank=True, default='', max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12), sys_base.models.charfield_is_number_validator]),
        ),
    ]
