# Generated by Django 4.1.3 on 2022-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0005_patient_id_alter_patient_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
