# Generated by Django 4.1.3 on 2022-11-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0006_appointmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='requestId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
