# Generated by Django 4.1.3 on 2022-11-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0007_alter_appointmentrequest_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='middlename',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middlename',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
