# Generated by Django 4.1.3 on 2022-11-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0008_alter_doctor_middlename_alter_patient_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='status',
            field=models.CharField(default='not considered', max_length=15),
        ),
    ]
