# Generated by Django 4.1.3 on 2022-12-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0009_alter_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_iin',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
