# Generated by Django 4.1.3 on 2022-11-30 14:18

from django.db import migrations, models
import sys_base.models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0009_appointmentrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.PositiveIntegerField(verbose_name=sys_base.models.Doctor)),
                ('slots', models.DateTimeField()),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='status',
            field=models.CharField(default='not considered', max_length=20),
        ),
    ]
