# Generated by Django 4.1.3 on 2022-11-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0009_appointmentrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialize',
            fields=[
                ('doctor_id', models.OneToOneField(db_column='iin', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sys_base.doctor')),
                ('spec', models.IntegerField(choices=[(0, 'Allergists'), (1, 'Cardiologists'), (2, 'Dermatologists'), (3, 'Endocrinologists'), (4, 'Physicians'), (5, 'Gastroenterologists')])),
            ],
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='status',
            field=models.CharField(default='not considered', max_length=20),
        ),
    ]
