# Generated by Django 4.1.3 on 2022-11-30 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0010_doctorschedule_alter_appointmentrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=60)),
                ('date', models.DateField(choices=[(0, datetime.date(2022, 11, 30)), (1, datetime.date(2022, 12, 1)), (2, datetime.date(2022, 12, 2)), (3, datetime.date(2022, 12, 3)), (4, datetime.date(2022, 12, 4)), (5, datetime.date(2022, 12, 5)), (6, datetime.date(2022, 12, 6))])),
                ('timeslot', models.IntegerField(choices=[(0, '09:00 – 09:30'), (1, '10:00 – 10:30'), (2, '11:00 – 11:30'), (3, '12:00 – 12:30'), (4, '13:00 – 13:30'), (5, '14:00 – 14:30'), (6, '15:00 – 15:30'), (7, '16:00 – 16:30'), (8, '17:00 – 17:30')])),
                ('patient_name', models.CharField(max_length=60)),
                ('patient_surname', models.CharField(max_length=60)),
                ('patient_contact', models.CharField(max_length=60)),
            ],
            options={
                'unique_together': {('doctor', 'date', 'timeslot')},
            },
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
    ]
