# Generated by Django 4.1.3 on 2022-12-06 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0010_remove_appointment_patient_appointment_patient_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sys_base.doctor'),
        ),
    ]
