# Generated by Django 4.1.3 on 2022-11-30 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0011_appointment_delete_doctorschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.IntegerField(choices=[(0, datetime.date(2022, 11, 30)), (1, datetime.date(2022, 12, 1)), (2, datetime.date(2022, 12, 2)), (3, datetime.date(2022, 12, 3)), (4, datetime.date(2022, 12, 4)), (5, datetime.date(2022, 12, 5)), (6, datetime.date(2022, 12, 6))]),
        ),
    ]
