# Generated by Django 4.1.3 on 2022-12-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0011_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.CharField(max_length=60),
        ),
    ]
