# Generated by Django 4.1.4 on 2022-12-07 18:03

from django.db import migrations, models
import django.db.models.deletion
import sys_base.models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0011_alter_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to=sys_base.models.user_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sys_base.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo_doctor',
            field=models.ImageField(default='null', null=True, upload_to=sys_base.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('NotMarried', 'Not Married')], max_length=30),
        ),
    ]
