# Generated by Django 4.1.3 on 2022-12-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0012_alter_appointment_date_alter_appointment_timeslot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'timeslot', 'status')},
        ),
    ]
