# Generated by Django 4.1.3 on 2022-11-30 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0012_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(choices=[(datetime.date(2022, 11, 30), datetime.date(2022, 11, 30)), (datetime.date(2022, 12, 1), datetime.date(2022, 12, 1)), (datetime.date(2022, 12, 2), datetime.date(2022, 12, 2)), (datetime.date(2022, 12, 3), datetime.date(2022, 12, 3)), (datetime.date(2022, 12, 4), datetime.date(2022, 12, 4)), (datetime.date(2022, 12, 5), datetime.date(2022, 12, 5)), (datetime.date(2022, 12, 6), datetime.date(2022, 12, 6))], max_length=60),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.CharField(choices=[('09:00 – 09:30', '09:00 – 09:30'), ('10:00 – 10:30', '10:00 – 10:30'), ('11:00 – 11:30', '11:00 – 11:30'), ('12:00 – 12:30', '12:00 – 12:30'), ('13:00 – 13:30', '13:00 – 13:30'), ('14:00 – 14:30', '14:00 – 14:30'), ('15:00 – 15:30', '15:00 – 15:30'), ('16:00 – 16:30', '16:00 – 16:30'), ('17:00 – 17:30', '17:00 – 17:30')], max_length=60),
        ),
    ]
