# Generated by Django 4.1.3 on 2022-12-01 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0013_merge_20221130_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.IntegerField(choices=[(0, datetime.date(2022, 12, 1)), (1, datetime.date(2022, 12, 2)), (2, datetime.date(2022, 12, 3)), (3, datetime.date(2022, 12, 4)), (4, datetime.date(2022, 12, 5)), (5, datetime.date(2022, 12, 6)), (6, datetime.date(2022, 12, 7))]),
        ),
        migrations.AlterField(
            model_name='specialize',
            name='spec',
            field=models.CharField(choices=[('Allergist', 'Allergist'), ('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologist'), ('Endocrinologist', 'Endocrinologist'), ('Physician', 'Physician'), ('Gastroenterologist', 'Gastroenterologist')], default='Allergist', max_length=30),
        ),
    ]
