# Generated by Django 4.1.3 on 2022-11-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0010_specialize_alter_appointmentrequest_status'),
        ('sys_base', '0013_alter_appointment_date_alter_appointment_timeslot'),
    ]

    operations = [
    ]
