# Generated by Django 4.1.3 on 2022-12-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0014_alter_appointment_date_alter_specialize_spec'),
        ('sys_base', '0014_merge_20221130_2318'),
    ]

    operations = [
    ]
