# Generated by Django 4.1.3 on 2022-12-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0015_merge_20221201_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(choices=[('2022-12-01', '2022-12-01'), ('2022-12-02', '2022-12-02'), ('2022-12-03', '2022-12-03'), ('2022-12-04', '2022-12-04'), ('2022-12-05', '2022-12-05'), ('2022-12-06', '2022-12-06'), ('2022-12-07', '2022-12-07')], max_length=60),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization_details_id',
            field=models.CharField(max_length=30),
        ),
    ]
