# Generated by Django 4.1.3 on 2022-12-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0017_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'timeslot')},
        ),
    ]
