# Generated by Django 4.1.3 on 2022-12-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0012_mymodel_appointment_patient_alter_appointment_date_and_more'),
        ('sys_base', '0018_alter_appointment_unique_together'),
    ]

    operations = [
    ]
