# Generated by Django 4.1.3 on 2022-12-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0020_alter_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
