# Generated by Django 4.1.3 on 2022-12-08 13:24

from django.db import migrations, models
import sys_base.models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_base', '0024_alter_doctor_photo_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo_doctor',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=sys_base.models.user_directory_path),
        ),
    ]
